---
title: "Focus List Demo"
format:
    revealjs:
        output-file: index.html
        height: 800 # default height and width ensure consistent behaviour on different screens
        width: 1250
filters:
    - focus-list
---

## `:::{.focus-list}` gives you a nice neat way to make lists that reveal incrementally with previous bullets fading out

```md
:::{.focus-list}
- I am the first list item
- I am the second list item
- And I am the third
:::
```

:::{.focus-list}
- I am the first list item
- I am the second list item
- And I am the third
:::


## And it works on dark backgrounds too {background-color="#000000"}

:::{.focus-list}
- I am the first list item
- I am the second list item
- And I am the third
:::

## And with nested lists

:::{.focus-list}
- I am the first list item
    - I am a subpoint of the first list item
        - I am a subpoint of a subpoint
- I am the second list item
- And I am the third
:::


## Add `.dim-parents` if you'd rather the parent faded out as well

```md
:::{.focus-list .dim-parents}
- I am the first list item
    - I am a subpoint of the first list item
:::
```

:::{.focus-list .dim-parents}
- I am the first list item
    - I am a subpoint of the first list item
        - I am a subpoint of a subpoint
- I am the second list item
- And I am the third
:::

## Nested lists work on dark backgrounds too {background-color="#000000"}

:::: {.columns}

::: {.column width='50%'}
#### Standard .focus-list
:::{.focus-list}
- I am the first list item
    - I am a subpoint of the first list item
        - I am a subpoint of a subpoint
- I am the second list item
- And I am the third
:::
:::

::: {.column width='50%'}
#### With .dim-parents
:::{.focus-list .dim-parents}
- I am the first list item
    - I am a subpoint of the first list item
        - I am a subpoint of a subpoint
- I am the second list item
- And I am the third
:::
:::

::::



# Why does this extension exist?

## Because this approach using native Quarto unfortunately doesn't work...

```md
:::{.incremental .fade-in-then-semi-out}
- I am the first list item
- I am the second list item
- And I am the third
:::
```

:::{.incremental .fade-in-then-semi-out}
- I am the first list item
- I am the second list item
- And I am the third
:::


## And this is a pain and runs the risk of lots of mismatched fragments (ask me how I know...)

```md
::: {.fragment .fade-in-then-semi-out}
- I am the first list item
:::
::: {.fragment .fade-in-then-semi-out}
- I am the second list item
:::
::: {.fragment}
- And I am the third
:::
```


::: {.fragment .fade-in-then-semi-out}
- I am the first list item
:::
::: {.fragment .fade-in-then-semi-out}
- I am the second list item
:::
::: {.fragment}
- And I am the third
:::
